In [1]:
pip install pandas numpy sqlalchemy psycopg2 -binary

Note: you may need to restart the kernel to use updated packages.

[optparse.groups]Usage:[/]
  c:\Users\Rahul Rana\AppData\Local\Programs\Python\Python 3.12\python.exe -m pip install \[options] <requirement specifier> \[package-index-options] ...
  c:\Users\Rahul Rana\AppData\Local\Programs\Python\Python 3.12\python.exe -m pip install \[options] -r <requirements file> \[package-index-options] ...
  c:\Users\Rahul Rana\AppData\Local\Programs\Python\Python 3.12\python.exe -m pip install \[options] [-e] <vcs project url> ...
  c:\Users\Rahul Rana\AppData\Local\Programs\Python\Python 3.12\python.exe -m pip install \[options] [-e] <local project path> ...
  c:\Users\Rahul Rana\AppData\Local\Programs\Python\Python 3.12\python.exe -m pip install \[options] <archive url/path> ...

no such option: -b

In [2]:
import pandas as pd
import numpy as np
import kagglehub
import psycopg2
path = kagglehub.dataset_download("belbino/us-tariff-and-trade-war-impact-dataset-2018-present")
print("Path to dataset files:", path)

c:\Users\Rahul Rana\AppData\Local\Programs\Python\Python 3.12\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\Rahul Rana\.cache\kagglehub\datasets\belbino\us-tariff-and-trade-war-impact-dataset-2018-present\126.archive...

100%|██████████| 161k/161k [00:00<00:00, 253kB/s]

Extracting files...
Path to dataset files: C:\Users\Rahul Rana\.cache\kagglehub\datasets\belbino\us-tariff-and-trade-war-impact-dataset-2018-present\versions\126

In [3]:
tariff_rates = pd.read_csv(f"{path}/tariff_rates.csv")
market_reaction = pd.read_csv(f"{path}/market_reaction.csv")
trade_balance = pd.read_csv(f"{path}/trade_balance.csv")
news_headlines = pd.read_csv(f"{path}/tariff_news_headlines.csv")

In [4]:
tariff_rates.head()

,date,country,product_category,tariff_rate_pct,announcement_source,headline,url
0,2018-03-08,Global,Steel,25.0,Section 232,Trump signs 25% steel tariffs under Section 232,NaN
1,2018-03-08,Global,Aluminum,10.0,Section 232,Trump signs 10% aluminum tariffs under Section...,NaN
2,2018-07-06,China,Tech/Industrial,25.0,Section 301,US imposes 25% tariffs on $34B of Chinese tech...,NaN
3,2019-09-01,China,Consumer Goods,15.0,Section 301,New 15% tariffs on Chinese consumer goods take...,NaN
4,2020-01-15,China,Phase 1 Deal,7.5,Phase 1 Agreement,US reduces China tariffs to 7.5% under Phase 1...,NaN

In [5]:
market_reaction.head()

,date,sp500,shanghai_composite,dxy,usd_cny,crude_oil_wti,steel_futures,aluminum_futures,soybeans
0,2020-01-02,3257.850098,3085.197998,96.849998,0.143633,61.180000,587.0,1812.50,944.25
1,2020-01-03,3234.850098,3083.785889,96.839996,0.143608,63.049999,590.0,1830.00,930.50
2,2020-01-06,3246.280029,3083.407959,96.669998,0.143585,63.270000,586.0,1842.00,932.75
3,2020-01-07,3237.179932,3104.802002,96.980003,0.143379,62.700001,591.0,1822.00,935.00
4,2020-01-08,3253.050049,3066.893066,97.300003,0.144001,59.610001,581.0,1802.75,938.25

In [6]:
trade_balance.head()

      date  us_trade_balance_bn
0  2020-01               -41443
1  2020-02               -37485
2  2020-03               -41407
3  2020-04               -51703
4  2020-05               -53786

In [7]:
news_headlines.head()

,date,headline,source,sentiment,url
0,2026-08-15,Canada needs to stop trying to appease Trump a...,Toronto Star,Neutral,https://www.thestar.com/business/opinion/canad...
1,2026-08-15,US consumer sentiment drops as Iran war fuels ...,The Daily Star,Neutral,https://www.thedailystar.net/business/news/us-...
2,2026-08-14,Her Great-Grandfather Founded a Jewelry Dynast...,Observer,Neutral,https://observer.com/2026/08/haverhill-leach-h...
3,2026-08-14,"With 100% Tariffs Looming, Indian Suppliers La...",WWD,Neutral,http://wwd.com/sourcing-journal/trade/100-perc...
4,2026-08-14,Meet the dedicated band of park pond admirals ...,Dailymail.com,Neutral,https://www.dailymail.com/news/article-1605311...

In [8]:
tariff_rates.info()
market_reaction.info()
trade_balance.info()
news_headlines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   date                 31 non-null     object
 1   country              31 non-null     object
 2   product_category     31 non-null     object
 3   tariff_rate_pct      31 non-null     float64
 4   announcement_source  31 non-null     object
 5   headline             31 non-null     object
 6   url                  16 non-null     object
dtypes: float64(1), object(6)
memory usage: 1.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1663 entries, 0 to 1662
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                1663 non-null   object
 1   sp500               1663 non-null   float64
 2   shanghai_composite  1548 non-null   float64
 3   dxy                 1663 non-null   float64
 4   usd_cny             1662 non-null   float64
 5   crude_oil_wti       1663 non-null   float64
 6   steel_futures       1662 non-null   float64
 7   aluminum_futures    1663 non-null   float64
 8   soybeans            1663 non-null   float64
dtypes: float64(8), object(1)
memory usage: 117.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   date                 78 non-null     object
 1   us_trade_balance_bn  78 non-null     int64
dtypes: int64(1), object(1)
memory usage: 1.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1352 entries, 0 to 1351
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       1352 non-null   object
 1   headline   1352 non-null   object
 2   source     1352 non-null   object
 3   sentiment  1352 non-null   object
 4   url        1352 non-null   object
dtypes: object(5)
memory usage: 52.9+ KB

In [9]:
tariff_rates.isnull().sum()
market_reaction.isnull().sum()
trade_balance.isnull().sum()
news_headlines.isnull().sum()

date         0
headline     0
source       0
sentiment    0
url          0
dtype: int64

In [10]:
for df in [tariff_rates, market_reaction, trade_balance, news_headlines]:
 df.columns = df.columns.str.lower().str.strip().str.replace(" ","_").str.replace("[^a-zA-Z0-9_]","",regex=True)

In [11]:
market_reaction = market_reaction.sort_values("date")

In [12]:
market_reaction["shanghai_composite"] = market_reaction["shanghai_composite"].ffill()
market_reaction["shanghai_composite"] = market_reaction["shanghai_composite"].bfill()

In [13]:
tariff_rates["url"] = tariff_rates["url"].fillna("Source Unspecified")

In [14]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

url = URL.create(
    drivername="postgresql+psycopg2",
    username="postgres",
    password="Rahul@rana7217",
    host="localhost",
    port=5432,
    database="market_intelligence_dashboard",
)

engine = create_engine(url)

with engine.connect() as conn:
    print("Connected successfully!")

Connected successfully!

In [15]:
tariff_rates.to_sql('tariff_rates', engine, if_exists='replace', index=False)
market_reaction.to_sql('market_reaction', engine, if_exists='replace', index=False)
trade_balance.to_sql('trade_balance', engine, if_exists='replace', index=False)
news_headlines.to_sql('news_headlines', engine, if_exists='replace', index=False)

print("Data successfully loaded into PostgreSQL!")

Data successfully loaded into PostgreSQL!