In [ ]:
%pip uninstall pandas
%pip install pandas==2.3.2

Found existing installation: pandas 2.3.2
Uninstalling pandas-2.3.2:
  Would remove:
    c:\users\rahul rana\appdata\local\programs\python\python 3.12\lib\site-packages\pandas-2.3.2.dist-info\*
    c:\users\rahul rana\appdata\local\programs\python\python 3.12\lib\site-packages\pandas.libs\msvcp140-a4c2229bdc2a2a630acdc095b4d86008.dll
    c:\users\rahul rana\appdata\local\programs\python\python 3.12\lib\site-packages\pandas\*
Proceed (Y/n)?
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas==2.3.2 in c:\users\rahul rana\appdata\local\programs\python\python 3.12\lib\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\rahul rana\appdata\local\programs\python\python 3.12\lib\site-packages (from pandas==2.3.2) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\rahul rana\appdata\roaming\python\python312\site-packages (from pandas==2.3.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\rahul rana\appdata\local\programs\python\python 3.12\lib\site-packages (from pandas==2.3.2) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\rahul rana\appdata\local\programs\python\python 3.12\lib\site-packages (from pandas==2.3.2) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\rahul rana\appdata\local\programs\python\python 3.12\lib\site-packages (from python-dateutil>=2.8.2->pandas==2.3.2) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Found existing installation: pandas 2.3.2
Uninstalling pandas-2.3.2:
  Would remove:
    c:\users\rahul rana\appdata\local\programs\python\python 3.12\lib\site-packages\pandas-2.3.2.dist-info\*
    c:\users\rahul rana\appdata\local\programs\python\python 3.12\lib\site-packages\pandas.libs\msvcp140-a4c2229bdc2a2a630acdc095b4d86008.dll
    c:\users\rahul rana\appdata\local\programs\python\python 3.12\lib\site-packages\pandas\*
Proceed (Y/n)?
Found existing installation: pandas 2.3.2
Uninstalling pandas-2.3.2:
  Would remove:
    c:\users\rahul rana\appdata\local\programs\python\python 3.12\lib\site-packages\pandas-2.3.2.dist-info\*
    c:\users\rahul rana\appdata\local\programs\python\python 3.12\lib\site-packages\pandas.libs\msvcp140-a4c2229bdc2a2a630acdc095b4d86008.dll
    c:\users\rahul rana\appdata\local\programs\python\python 3.12\lib\site-packages\pandas\*
Proceed (Y/n)?

:

In [6]:
import pandas as pd
import numpy as np
import kagglehub
import psycopg2
path = kagglehub.dataset_download("belbino/us-tariff-and-trade-war-impact-dataset-2018-present")
print("Path to dataset files:", path)

c:\Users\Rahul Rana\AppData\Local\Programs\Python\Python 3.12\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\Rahul Rana\.cache\kagglehub\datasets\belbino\us-tariff-and-trade-war-impact-dataset-2018-present\104.archive...

100%|██████████| 143k/143k [00:00<00:00, 223kB/s]

Extracting files...
Path to dataset files: C:\Users\Rahul Rana\.cache\kagglehub\datasets\belbino\us-tariff-and-trade-war-impact-dataset-2018-present\versions\104

In [35]:
tariff_rates = pd.read_csv(f"{path}/tariff_rates.csv")
market_reaction = pd.read_csv(f"{path}/market_reaction.csv")
trade_balance = pd.read_csv(f"{path}/trade_balance.csv")
news_headlines = pd.read_csv(f"{path}/tariff_news_headlines.csv")

In [58]:
tariff_rates.head()

,date,country,product_category,tariff_rate_pct,announcement_source,headline,url
0,2018-03-08,Global,Steel,25.0,Section 232,Trump signs 25% steel tariffs under Section 232,NaN
1,2018-03-08,Global,Aluminum,10.0,Section 232,Trump signs 10% aluminum tariffs under Section...,NaN
2,2018-07-06,China,Tech/Industrial,25.0,Section 301,US imposes 25% tariffs on $34B of Chinese tech...,NaN
3,2019-09-01,China,Consumer Goods,15.0,Section 301,New 15% tariffs on Chinese consumer goods take...,NaN
4,2020-01-15,China,Phase 1 Deal,7.5,Phase 1 Agreement,US reduces China tariffs to 7.5% under Phase 1...,NaN

In [61]:
market_reaction.head()

,date,sp500,shanghai_composite,dxy,usd_cny,crude_oil_wti,steel_futures,aluminum_futures,soybeans
0,2020-01-02,3257.850098,3085.197998,96.849998,0.143633,61.180000,587.0,1812.50,944.25
1,2020-01-03,3234.850098,3083.785889,96.839996,0.143608,63.049999,590.0,1830.00,930.50
2,2020-01-06,3246.280029,3083.407959,96.669998,0.143585,63.270000,586.0,1842.00,932.75
3,2020-01-07,3237.179932,3104.802002,96.980003,0.143379,62.700001,591.0,1822.00,935.00
4,2020-01-08,3253.050049,3066.893066,97.300003,0.144001,59.610001,581.0,1802.75,938.25

In [56]:
trade_balance.head()

      date  us_trade_balance_bn
0  2020-01               -41443
1  2020-02               -37485
2  2020-03               -41407
3  2020-04               -51703
4  2020-05               -53786

In [62]:
news_headlines.head()

,date,headline,source,sentiment,url
0,2026-07-24,"China opposes new US tariffs, warns against tr...",Vanguard,Positive,https://www.vanguardngr.com/2026/07/china-oppo...
1,2026-07-24,Morning Bid: Running on empty,Yahoo Entertainment,Neutral,https://finance.yahoo.com/news/morning-bid-run...
2,2026-07-24,Liberty Justice Center Files First Lawsuit Cha...,Reason,Positive,https://reason.com/volokh/2026/07/24/liberty-j...
3,2026-07-24,Brazil’s tariff rate rises to 18% after Trump’...,Crypto Briefing,Positive,https://cryptobriefing.com/brazil-tariff-rate-...
4,2026-07-24,Trump’s Tariff Sham,The American Prospect,Negative,https://prospect.org/2026/07/24/trumps-tariff-...

In [25]:
tariff_rates.info()
market_reaction.info()
trade_balance.info()
news_headlines.info()

<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   date                 43 non-null     str
 1   country              43 non-null     str
 2   product_category     43 non-null     str
 3   tariff_rate_pct      43 non-null     float64
 4   announcement_source  43 non-null     str
 5   headline             43 non-null     str
 6   url                  28 non-null     str
dtypes: float64(1), str(6)
memory usage: 2.5 KB
<class 'pandas.DataFrame'>
RangeIndex: 1648 entries, 0 to 1647
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                1648 non-null   str
 1   sp500               1648 non-null   float64
 2   shanghai_composite  1533 non-null   float64
 3   dxy                 1648 non-null   float64
 4   usd_cny             1647 non-null   float64
 5   crude_oil_wti       1648 non-null   float64
 6   steel_futures       1647 non-null   float64
 7   aluminum_futures    1648 non-null   float64
 8   soybeans            1648 non-null   float64
dtypes: float64(8), str(1)
memory usage: 116.0 KB
<class 'pandas.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   date                 77 non-null     str
 1   us_trade_balance_bn  77 non-null     int64
dtypes: int64(1), str(1)
memory usage: 1.3 KB
<class 'pandas.DataFrame'>
RangeIndex: 1100 entries, 0 to 1099
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       1100 non-null   str
 1   headline   1100 non-null   str
 2   source     1100 non-null   str
 3   sentiment  1100 non-null   str
 4   url        1100 non-null   str
dtypes: str(5)
memory usage: 43.1 KB

In [26]:
tariff_rates.isnull().sum()
market_reaction.isnull().sum()
trade_balance.isnull().sum()
news_headlines.isnull().sum()

date         0
headline     0
source       0
sentiment    0
url          0
dtype: int64

In [66]:
for df in [tariff_rates, market_reaction, trade_balance, news_headlines]:
 df.columns = df.columns.str.lower().str.strip().str.replace(" ","_").str.replace("[^a-zA-Z0-9_]","",regex=True)

In [67]:
market_reaction = market_reaction.sort_values("date")

In [68]:
market_reaction["shanghai_composite"] = market_reaction["shanghai_composite"].ffill()
market_reaction["shanghai_composite"] = market_reaction["shanghai_composite"].bfill()

In [70]:
tariff_rates["url"] = tariff_rates["url"].fillna("Source Unspecified")

In [71]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\rahul rana\appdata\local\programs\python\python 3.12\lib\site-packages (2.0.27)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\rahul rana\appdata\local\programs\python\python 3.12\lib\site-packages (from sqlalchemy) (4.13.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\rahul rana\appdata\local\programs\python\python 3.12\lib\site-packages (from sqlalchemy) (3.2.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [95]:
from sqlalchemy import create_engine
db_user = "postgres"
db_password = "Rahul@rana7217"
db_host = "localhost"
db_port = "5432"
db_name = "market_intelligence_dashboard"

# Create Database Engine
engine = create_engine(f"postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}")

In [101]:
import pandas
print(pandas.__version__)
print(pandas.__file__)

3.0.5
c:\Users\Rahul Rana\AppData\Local\Programs\Python\Python 3.12\Lib\site-packages\pandas\__init__.py

In [104]:
python -m %pip uninstall pandas sqlalchemy -y
python -m %pip install pandas sqlalchemy psycopg2-binary

SyntaxError: invalid syntax (2102738446.py, line 1)